/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayOnlineRouteImport } from './routes/play.online'
import { Route as PlayModeRouteImport } from './routes/play.$mode'
import { Route as PlayGameGameIdRouteImport } from './routes/play.game.$gameId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOnlineRoute = PlayOnlineRouteImport.update({
  id: '/play/online',
  path: '/play/online',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayModeRoute = PlayModeRouteImport.update({
  id: '/play/$mode',
  path: '/play/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameGameIdRoute = PlayGameGameIdRouteImport.update({
  id: '/play/game/$gameId',
  path: '/play/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/friends': typeof FriendsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/play/$mode': typeof PlayModeRoute
  '/play/online': typeof PlayOnlineRoute
  '/play/game/$gameId': typeof PlayGameGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/friends': typeof FriendsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/play/$mode': typeof PlayModeRoute
  '/play/online': typeof PlayOnlineRoute
  '/play/game/$gameId': typeof PlayGameGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/friends': typeof FriendsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/play/$mode': typeof PlayModeRoute
  '/play/online': typeof PlayOnlineRoute
  '/play/game/$gameId': typeof PlayGameGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/friends'
    | '/privacy-policy'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/terms'
    | '/play/$mode'
    | '/play/online'
    | '/play/game/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/friends'
    | '/privacy-policy'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/terms'
    | '/play/$mode'
    | '/play/online'
    | '/play/game/$gameId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/friends'
    | '/privacy-policy'
    | '/profile'
    | '/settings'
    | '/shop'
    | '/terms'
    | '/play/$mode'
    | '/play/online'
    | '/play/game/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  FriendsRoute: typeof FriendsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  PlayModeRoute: typeof PlayModeRoute
  PlayOnlineRoute: typeof PlayOnlineRoute
  PlayGameGameIdRoute: typeof PlayGameGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/online': {
      id: '/play/online'
      path: '/play/online'
      fullPath: '/play/online'
      preLoaderRoute: typeof PlayOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$mode': {
      id: '/play/$mode'
      path: '/play/$mode'
      fullPath: '/play/$mode'
      preLoaderRoute: typeof PlayModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/game/$gameId': {
      id: '/play/game/$gameId'
      path: '/play/game/$gameId'
      fullPath: '/play/game/$gameId'
      preLoaderRoute: typeof PlayGameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  FriendsRoute: FriendsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  PlayModeRoute: PlayModeRoute,
  PlayOnlineRoute: PlayOnlineRoute,
  PlayGameGameIdRoute: PlayGameGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
